### ISSUE TITLE
Name of the layer

### ISSUE THREAD

**Issue by Paebbels** [edaa-org/pyEDAA.Configure#3]
@umarcor how to name the "configuration" layer?

1. `pyEDAA.Configure`
2. `pyEDAA.Configuration`
3. `pyEDAA.CLIConfiguration`
4. `pyEDAA.Setup`
5. `pyEDAA.ToolSetup` ✔️ 

Maybe the second form is the better one.
I don't know why I called everything "Configure"...

-----------------

Can you please:
* [x] Add the selected name to the SVG generation and generate appropriate images. (edaa-org/edaa-org.github.io#4)
* [x] Add the generated logo to this repository. (#4)
* [x] Add the generated logo to the edaa-org website in section "Interacting with CLIs". (edaa-org/edaa-org.github.io#4)

I'll take care of renaming if name is changed for
* [x] Codacy name (unregister)
  Unregister from Codacy before changing repository name.
* [x] Repository name
* [x] Package name
* [ ] PyPI name
* [ ] Codacy name (register)

**Comment by umarcor** [comment]
Should it be `Configuration` or `Configurations`?

**Comment by Paebbels** [comment]
I think it should be singular as we have `ProjectModel` or `CLITool`.

**Comment by Paebbels** [comment]
Hmmm we have `pyEDAA.Reports` in plural ... (we might need to think about it later)

**Comment by umarcor** [comment]
> Add the generated logo to the edaa-org website in section "Projects and Configurations".

I think pyEDAA.Configurations belongs to [Interacting with CLIs](https://edaa-org.github.io/CLI.html), because it is related to the configuration of the location of CLI tools. Conversely, the "Projects and Configurations" is about YAML/JSON files describing a project, such as `.core` (CAPI2) files.

**Comment by Paebbels** [comment]
Oh, you're right, it's a difference kind of configuration :).

I adjusted the issue text.

**Comment by Paebbels** [comment]
Or is it then a `pyEDAA.CLIConfiguration` to keep normal `Configuration` name free for later usage?

**Comment by umarcor** [comment]
I would actually call this `Setup` (or `Setups`), instead of `Configuration`. In essence, this layer describes (or finds out) which is the existing tool setup/installation on the system. That avoids misunderstandings with "other configurations".
